paru = ["snapper_bcachefs", "grub-git"]

files = [
  "bcachefs/etc/mkinitcpio.conf",
  "bcachefs/etc/snapper/configs",
  "bcachefs/{home}/.cache/paru/diff/grub-git.diff.safe",
]

service = ["snapper-timeline.timer", "snapper-cleanup.timer"]
