imports = ["common", "filesystems/btrfs", "laptop_temp", "virtualbox"]

paru = [
  "amd-ucode",
  "amdgpu_top-bin",
  "amdvlk",
  "antimicrox",
  "batsignal",
  "bindfs",
  "bluez-utils",
  "cups",
  "evremap-git",
  "foliate",
  "linux-firmware-amdgpu",
  "linux-firmware-realtek",
  "linux-firmware-other",
  "linux-firmware-whence",
  # "opencl-amd",
  "snap-pac",
  "sshfs",
  "usbguard",
  "wezterm",
  "wireless_tools",
  "xf86-video-amdgpu",
]

service = [
  "bluetooth",
  "cups",
  "cups.path",
  "cups.socket",
  "evremap",
  "macchanger@wlp2s0",
  "usbguard",
]
