imports = ["common", "filesystems/btrfs", "laptop_temp", "virtualbox"]

paru = [
  "amd-ucode",
  "amdgpu_top-bin",
  "amdvlk",
  "antimicrox",
  "bindfs",
  "cups",
  "evremap-git",
  "foliate",
  "losslesscut-git",
  # "opencl-amd",
  "snap-pac",
  "sshfs",
  "usbguard",
  "wezterm",
  "wireless_tools",
  "xf86-video-amdgpu",
  "zed",
]

service = [
  "bluetooth",
  "cups",
  "cups.path",
  "cups.socket",
  "evremap",
  "macchanger@wlp2s0",
  "usbguard",
]
