paru = ["devtools", "lld", "llvm", "rust-bindgen"]

files = [
  "/home/julius/linux/pc",
  "/home/julius/linux/laptop",
  "/home/julius/linux/PKGBUILD",
  "/home/julius/linux/.config.minimal.pc",
  "/home/julius/linux/.config.minimal.laptop",
]
