paru = [
  "devtools",
  "lld",
  "llvm",
  "rust-bindgen",
  "linux-custom",
  "linux-custom-headers",
]

files = [
  "/{home}/linux/pc",
  "/{home}/linux/laptop",
  "/{home}/linux/PKGBUILD",
  "/{home}/linux/.config.minimal.pc",
  "/{home}/linux/.config.minimal.laptop",
]
