paru = [
  "lutris",
  "steam-native-runtime",
  # Hollow knight
  "lumafly",
  "mono",
  # Ror2
  "r2modman-bin",
]

files = [
  "/home/julius/.games",
  # Lutris
  "/home/julius/.config/lutris",
  "/home/julius/.local/share/lutris/pga.db",
  "/home/julius/.local/share/yuzu",
  # Save files
  "/home/julius/.config/unity3d",
  "/home/julius/.local/share/Balatro",
  "/home/julius/.local/share/Celeste",
]
