paru = [
  "love",
  "lutris",
  "steam-native-runtime",
  # Hollow knight
  "lumafly",
  "mono",
  # Ror2
  "r2modman-bin",
]

files = [
  "/{home}/.games",
  # Lutris
  "/{home}/.config/love",
  "/{home}/.config/lutris",
  "/{home}/.local/share/lutris/pga.db",
  "/{home}/.local/share/yuzu",
  # Save files
  "/{home}/.config/unity3d",
  "/{home}/.local/share/Celeste",
  "/{home}/.local/share/love",
  "/{home}/.config/r2modmanPlus-local",
]
