cargo = [
  "--git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide",
]

system = [
  "stylua", # conform.nvim
  "lua-language-server",
  "python-pylatexenc", # render-markdown.nvim
]
