paru = ["anki-bin", "geogebra-6-bin", "inkscape", "xournalpp"]
cargo = ["typst-cli", "--git https://github.com/jullanggit/anksidian anksidian"]
files = [
  "/{home}/.config/xournalpp",
  "/{home}/.local/share/Anki2",
  "/{home}/.config/anksidian",
]
flatpak = "page.codeberg.lo_vely.Nucleus"
