paru = ["anki", "geogebra-6-bin", "rnote-git", "xournalpp"]
cargo = [
  "typst-cli",
  "--git https://github.com/Myriad-Dreamin/tinymist tinymist",
]
files = ["/{home}/.config/xournalpp", "/{home}/.local/share/Anki2"]
