imports = ["cachyos"]

paru = [
  "arch-install-scripts",
  "base",
  "base-devel",
  "coreutils-hybrid-git",
  "cronie",
  "linux-firmware",
  "linux-headers",
  "logrotate",
  "man-db",
  "man-pages",
  "mkinitcpio",
  "networkmanager",
  "openssh",
  "pavucontrol",
  "power-profiles-daemon",
  "rate-mirrors",
  "reflector",
  "sshfs",
  "update-grub",
  "usbutils",
  "xclip",
]

cargo = [
  "--git https://github.com/jullanggit/cargo_install_reconstructor cargo_install_reconstructor",
  "--git https://github.com/jullanggit/dots dots",
  "--git https://github.com/jullanggit/meta meta",
  "-F git --git https://github.com/Morganamilo/paru paru",
]

service = [
  "avahi-daemon",
  "avahi-daemon.socket",
  "cronie",
  "NetworkManager",
  "NetworkManager-dispatcher",
  "NetworkManager-wait-online",
  "shut-down-at-night.timer",
  "sshd",
]

files = [
  "/etc/pacman.conf",
  "/etc/pacman.d/mirrorlist",
  "/etc/systemd/resolved.conf",
  "/etc/systemd/system/macchanger@.service",
  "/etc/systemd/system/shut-down-at-night.service",
  "/etc/systemd/system/shut-down-at-night.timer",
  "{hostname}/home/julius/.ssh",
  "/home/julius/.config/dots",
  "/home/julius/.config/paru/paru.conf",
]
