imports = ["cachyos"]

paru = [
  "arch-install-scripts",
  "base",
  "base-devel",
  "coreutils-uutils",
  "cronie",
  "linux-headers",
  "logrotate",
  "lvm2",
  "man-db",
  "man-pages",
  "mkinitcpio",
  "networkmanager",
  "openssh",
  "pavucontrol",
  "power-profiles-daemon",
  "rate-mirrors",
  "reflector",
  "sshfs",
  "update-grub",
  "usbutils",
  "xclip",
]

cargo = [
  "atem",
  "atem-dots",
  "--git https://github.com/jullanggit/cargo_install_reconstructor cargo_install_reconstructor",
  "-F git --git https://github.com/Morganamilo/paru paru",
  "--git https://github.com/jullanggit/sleep-timer sleep-timer",
]

service = [
  "avahi-daemon",
  "avahi-daemon.socket",
  "cleanup_packages.timer",
  "cronie",
  "NetworkManager",
  "NetworkManager-dispatcher",
  "NetworkManager-wait-online",
  "start_sleep_timer",
  "sshd",
]

files = [
  "/etc/pacman.conf",
  "/etc/pacman.d/mirrorlist",
  "/etc/systemd/resolved.conf",
  "/etc/systemd/system/cleanup_packages.timer",
  "/etc/systemd/system/cleanup_packages.service",
  "{hostname}/{home}/.ssh",
  "/{home}/.config/dots",
  "/{home}/.config/paru/paru.conf",
  "/{home}/.config/sleep-timer",
]

files_copy = [
  "/etc/systemd/system/macchanger@.service",
  "/etc/systemd/system/start_sleep_timer.service",
]
