paru = [
  "btop",
  "fastfetch",
  "fish",
  "fisher",
  "helix",
  "shlorem",
  "starship",
  "ttf-hack",
  "ttf-hack-nerd",
  "ttf-nerd-fonts-symbols-mono",
  "vim",
  "wl-clipboard",
]

cargo = [
  "bat",
  "-F clipboard broot",
  "eza",
  "ripgrep",
  "repgrep",
  "uwuify",
  "zoxide",
]

files = [
  "/{home}/.wezterm.lua",
  "/{home}/.config/fastfetch/config.jsonc",
  "/{home}/.config/fish",
  "/{home}/.config/helix",
  "/{home}/.config/starship.toml",
  "/root/.config/fish",
]
