paru = [
  "btop",
  "fastfetch",
  "fish",
  "fisher",
  "helix",
  "shlorem",
  "starship",
  "ttf-hack",
  "ttf-hack-nerd",
  "vim",
  "wezterm",
  "wl-clipboard",
]

cargo = [
  "bat",
  "-F clipboard broot",
  "eza",
  "--git https://github.com/jullanggit/ferris_if_rust ferris_if_rust",
  "ripgrep",
  "repgrep",
  "uwuify",
  "zoxide",
]

files = [
  "/home/julius/.wezterm.lua",
  "/home/julius/.config/fastfetch/config.jsonc",
  "/home/julius/.config/fish",
  "/root/.config/fish",
]
